apiVersion: v1
kind: LimitRange
metadata:
  name: my-limit-range
spec:
  limits:
  - type: Container
    default:
      memory: "128Mi"
      cpu: "500m"
    defaultRequest:
      memory: "64Mi"
      cpu: "250m"
    max:
      memory: "256Mi"
      cpu: "1000m"
    min:
      memory: "64Mi"
      cpu: "250m"
    maxLimitRequestRatio:
      memory: "2"
      cpu: "2"
  - type : Pod
    default:
      memory: "128Mi"
      cpu: "500m"
    defaultRequest:
      memory: "64Mi"
      cpu: "250m"
    max:
      memory: "256Mi"
      cpu: "1000m"
    min:
      memory: "64Mi"
      cpu: "250m"
    maxLimitRequestRatio:
      memory: "2"
      cpu: "2"
