apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-with-node-affinity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-with-node-affinity
  template:
    metadata:
      labels:
        app: my-app-with-node-affinity
    spec:
      containers:
      - name: myspringapp
        image: my-spring-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
