apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quotas
  namespace: dev
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "1Gi"
    limits.cpu: "1000m"
    limits.memory: "2Gi"

    pods: "5"
    services: "5"
    replicationcontrollers: "5"
    persistentvolumeclaims: "5"
    secrets: "5"
    configmaps: "5"

    requests.storage: "10Gi"