apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-with-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-with-sidecar
  template:
    metadata:
      labels:
        app: my-app-with-sidecar
    spec:
      volumes:
        - name: app-logs # Shared volume for logs
          emptyDir: {}
      containers: # Main application container
        - name: my-main-app
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "while true; do echo 'App log entry: $(date)'; sleep 1; done > /var/log/my-app.log",
            ]
          volumeMounts:
            - name: app-logs
              mountPath: /var/log
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
        - name: log-shipper # Sidecar container
          image: fluentd:latest # Or a custom log shipping agent
          command: ["sh", "-c", "tail -F /var/log/my-app.log"] # Simulate shipping logs
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          volumeMounts:
            - name: app-logs
              mountPath: /var/log # Mount the same volume as the main app
