apiVersion: v1
kind: Pod
metadata:
  name: test-pod-sa
spec:
  serviceAccountName: my-service-account
  containers:
    - name: busybox-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
  restartPolicy: Never

  # if somebody access the shell
  # kubectl get pods -n default ALLOWED
  # kubectl get pods -n kube-system DENIED