apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-with-pvc
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: busybox
        command: ["/bin/sh", "-c", "while true; do sleep 10; done;"]
        volumeMounts:
        - name: mypv
          mountPath: /data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
      volumes:
      - name: mypv
        persistentVolumeClaim:
          claimName: mypvc
