apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-with-probe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-with-probe
  template:
    metadata:
      labels:
        app: my-app-with-probe
    spec:
      containers:
      - name: myspringapp
        image: my-spring-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /health/startup
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 30  # allows up to 5 minutes for startup (30 x 10s)
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 5 # wait 5 seconds before first check
          periodSeconds: 5 # check every 5 seconds
          timeoutSeconds: 2 # timeout after 2 seconds
          failureThreshold: 3 # fail after 3 consecutive failures
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
