apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  labels:
    app: my-app
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      environment: dev
  template:
    metadata:
      labels:
        app: my-app
        environment: dev
    spec:
      containers:
        - name: my-nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: nginx_conf
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: nginx_conf
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
